# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2025-2026 ViralMint Contributors
from sqlalchemy import Column, String, Text, Integer, Float, DateTime, Boolean
from datetime import datetime
from uuid import uuid4
from backend.database import Base

# Longest string accepted as a `niche`. A real niche is a search phrase
# ("stoicism", "personal finance for gen z"), never a sentence. Shared by the
# writer (agents/generator._resolve_row_niche) and any reader so the two can't
# drift: the pipeline used to store the analyzer's prose `topic_angle` here,
# producing 250-450 char "niches". The column is String(200) but SQLite does
# not enforce VARCHAR length, so it failed silently.
NICHE_MAX_CHARS = 100


class GeneratedVideo(Base):
    __tablename__ = "generated_videos"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid4()))
    user_id = Column(String(36), default="local", index=True)
    source_scout_result_id = Column(String(36), nullable=True)
    source_downloaded_video_id = Column(String(36), nullable=True)

    # Script + metadata
    title = Column(Text, nullable=True)
    script = Column(Text, nullable=True)
    niche = Column(String(200), nullable=True)

    # Files
    video_path = Column(Text, nullable=True)
    audio_path = Column(Text, nullable=True)
    thumbnail_path = Column(Text, nullable=True)

    # Generation params
    aspect_ratio = Column(String(10), default="9:16")    # 9:16 | 16:9
    duration_seconds = Column(Integer, nullable=True)
    voice_id = Column(String(100), nullable=True)
    gen_tier = Column(String(20), default="standard")    # standard | premium | clip_extraction
    source_type = Column(String(30), nullable=True)      # "clip_extraction" | null

    # Clip extraction fields
    clip_start_seconds = Column(Float, nullable=True)       # Start time in source video
    clip_end_seconds = Column(Float, nullable=True)         # End time in source video
    clip_virality_score = Column(Float, nullable=True)      # AI-scored 1-10
    clip_hook_score = Column(Float, nullable=True)          # Hook strength 1-10
    clip_hook_type = Column(String(30), nullable=True)      # curiosity_gap | contrarian | emotional_peak | question | number_promise | story_loop | actionable_tip | shocking_claim | general
    clip_virality_reason = Column(Text, nullable=True)      # Why this clip is viral
    clip_score_breakdown_json = Column(Text, nullable=True) # JSON: {flow, value, trend, shareability} each 1-10 — vidiq-style sub-scores behind the virality_score. Hook lives on clip_hook_score so it's not duplicated here.
    caption_status = Column(String(20), nullable=True)      # "applied" | "skipped" (caption_style="none") | "no_segments" (silent clip) | "failed" | "extract_failed" | null
    metadata_status = Column(String(20), nullable=True)     # "ai_generated" | "fallback" | null
    # Where this clip's window came from: "ai" (the viral picker chose it) |
    # "manual" (a bench cut or an explicit time range) | "duration_fallback"
    # (the picker found nothing, so the run cut evenly-spaced time slices).
    # NULL on rows that predate the column. A job-level count cannot say WHICH
    # clips to distrust; this can.
    clip_selection = Column(String(20), nullable=True)

    # Upload tracking
    youtube_video_id = Column(String(50), nullable=True)
    tiktok_publish_id = Column(String(100), nullable=True)
    instagram_media_id = Column(String(100), nullable=True)
    uploaded_platforms_json = Column(Text, default="[]")  # ["youtube", "tiktok", "instagram"]
    video_path_landscape = Column(Text, nullable=True)   # 16:9 version (if exported)

    # Platform metadata (generated by AI for each platform)
    youtube_title = Column(Text, nullable=True)
    youtube_description = Column(Text, nullable=True)
    youtube_tags_json = Column(Text, nullable=True)
    tiktok_title = Column(Text, nullable=True)
    tiktok_description = Column(Text, nullable=True)

    # Cost tracking
    estimated_cost_usd = Column(Float, default=0.0)

    status = Column(String(20), default="draft")
    # statuses: draft | ready | uploading | uploaded | failed

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, onupdate=datetime.utcnow)
